FROM ubuntu:latest

ENTRYPOINT [ "echo", "Hello " ]

CMD [ "World"]


#### v1:
# FROM nginx:latest

# RUN apt-get update
# RUN apt-get install vim -y

#### v2:
# FROM nginx:latest

# WORKDIR /usr/share/nginx/html

# RUN apt-get update && \
#     apt-get install vim -y

# COPY . /usr/share/nginx/html

#### v3:
# FROM ubuntu:latest

# CMD [ "echo", "Hello World"]

#### v3:
# FROM ubuntu:latest

# ENTRYPOINT [ "echo", "Hello " ]

# CMD [ "World"]